spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/department/**
        - id: ORGANISATION-SERVICE
          uri: lb://ORGANISATION-SERVICE
          predicates:
            - Path=/api/organisation/**
  zipkin:
    base-url:  http://127.0.0.1:9411/
           
eureka:
  instance:
    client:
      serverUrl:
        defaultZone=http://localhost:8071/eureka
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9071
    
        
        
      