server:
  port: 9095
spring:
  application:
    name: ORGANISATION-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/organisation_db
    username: root
    password: Admin@1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8080
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      refresh:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics,busrefresh,busenv
